before_install:
  - wget https://releases.hashicorp.com/terraform/0.11.10/terraform_0.11.10_linux_amd64.zip -O /tmp/tf.zip
  - unzip -d bin/ /tmp/tf.zip
  - export PATH=$PATH:$PWD/bin
script:
  - terraform fmt -check=true
  - terraform validate -check-variables=false
